version: "2"

linters:
  enable:
    - govet
    - revive
  exclusions:
    paths:
      - gen_*\.go
      - _test\.go

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - gen_*\.go
      - _test\.go
