name: setup tools
description: Set up project tools with aqua and mise.

inputs:
  aqua:
    description: Install aqua-managed tools.
    default: "true"
runs:
  using: composite
  steps:
    - if: ${{ inputs.aqua == 'true' }}
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.60.1
        aqua_opts: ""
    - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      with:
        cache: false
