name: setup tools
description: Set up project tools with aqua and mise.

inputs:
  aqua:
    description: Install aqua-managed tools.
    default: "true"
runs:
  using: composite
  steps:
    - if: ${{ inputs.aqua == 'true' }}
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.57.2
        aqua_opts: ""
    - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        cache: false
