on:
  workflow_call:
    inputs:
      gh-app-client-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true

permissions: {}

jobs:
  codeql:
    uses: ./.github/workflows/_codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  test:
    uses: ./.github/workflows/_test.yml
    with:
      gh-app-client-id: ${{ inputs.gh-app-client-id }}
    secrets:
      gh-app-private-key: ${{ secrets.gh-app-private-key }}
    permissions:
      contents: read
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: load env
        run: |
          grep -v '#' .github/linters/superlinter.env >> "$GITHUB_ENV"
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: gh-app-token
        with:
          client-id: ${{ inputs.gh-app-client-id }}
          private-key: ${{ secrets.gh-app-private-key }}
          permission-issues: write
          permission-pull-requests: write
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # for super-linter
          fetch-depth: 0
          persist-credentials: false
      - uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: false

      - name: Update sticky PR comment
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: super-linter-report
          path: ${{ github.workspace }}/super-linter-output/super-linter-summary.md
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}
