on:
  workflow_call:
    inputs:
      gh-app-client-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true

permissions: {}

jobs:
  codeql:
    uses: ./.github/workflows/_codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  test:
    uses: ./.github/workflows/_test.yml
    with:
      gh-app-client-id: ${{ inputs.gh-app-client-id }}
    secrets:
      gh-app-private-key: ${{ secrets.gh-app-private-key }}
    permissions:
      contents: read
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # for super-linter
          fetch-depth: 0
          persist-credentials: false
      - name: load env
        run: |
          grep -v '#' .github/linters/superlinter.env >> "$GITHUB_ENV"
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: gh-app-token
        with:
          client-id: ${{ inputs.gh-app-client-id }}
          private-key: ${{ secrets.gh-app-private-key }}
          permission-issues: write
          permission-pull-requests: write
      - uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: false

      - name: Update sticky PR comment
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          header: super-linter-report
          path: ${{ github.workspace }}/super-linter-output/super-linter-summary.md
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}
