on:
  workflow_call:

permissions: {}

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    permissions:
      contents: read
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: load env
        run: |
          grep -v '#' .github/linters/superlinter.env >> "$GITHUB_ENV"
      - uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
