on:
  workflow_call:
    inputs:
      gh-app-client-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.57.2
          aqua_opts: ""
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: build
        run: make build
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: e2e-test
        run: make e2e-test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ inputs.gh-app-client-id }}
          private-key: ${{ secrets.gh-app-private-key }}
      - name: e2e-test-github-app
        run: make e2e-test
        env:
          GH_APP_CLIENT_ID: ${{ inputs.gh-app-client-id }}
          GH_INSTALLATION_ID: ${{ steps.app-token.outputs.installation-id }}
          GH_PRIVATE_KEY: ${{ secrets.gh-app-private-key }}
