on:
  workflow_call:
    inputs:
      gh-app-client-id:
        required: true
        type: string
    secrets:
      gh-app-private-key:
        required: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-tools
      - name: build
        run: make build
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: e2e-test
        run: make e2e-test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ inputs.gh-app-client-id }}
          private-key: ${{ secrets.gh-app-private-key }}
      - name: e2e-test-github-app
        run: make e2e-test
        env:
          GH_APP_CLIENT_ID: ${{ inputs.gh-app-client-id }}
          GH_INSTALLATION_ID: ${{ steps.app-token.outputs.installation-id }}
          GH_PRIVATE_KEY: ${{ secrets.gh-app-private-key }}
