name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      gh-app-client-id: ${{ vars.GH_APP_RELEASE_CLIENT_ID }}
    secrets:
      gh-app-private-key: ${{ secrets.GH_APP_RELEASE_PRIVATE_KEY }}
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write

  check-result:
    needs: ci
    runs-on: ubuntu-slim
    if: ${{ always() && needs.ci.result != 'success' }}
    steps:
      - name: exit with failure
        run: exit 1
